### ISSUE TITLE
Adding text below loader

### ISSUE THREAD

**Issue by willemevenwel** [shaminmeerankutty/react-fullscreen-loading#2]
hi,

sorry for silly question, im very new to react and components. i like your fullscreen loader, but need to add text to it, like "Loading, please wait...".

could you assist in the matter please?

regards

willem

**Comment by shamin** [comment]
Hi Willem,

What you want is really easy to achieve. Try to go through and understand the source code it is very easy and what you want can be achieved with the following

- Copy https://github.com/shamin/react-fullscreen-loading/blob/master/lib/loading.js and https://github.com/shamin/react-fullscreen-loading/blob/master/lib/styles.css files to your react project
- Add `Loading, please wait...` to this line https://github.com/shamin/react-fullscreen-loading/blob/34549eead619e5ae640337a4a4266e69edd15a3d/lib/loading.js#L16 
- Style it using css.

If you need more help feel free to comment on the issue. Happy to help you.

**Comment by willemevenwel** [comment]
Hey shamin,

Thanks so much for your already thorough answer. I'm kinda getting the hang of it, but getting a weird error which I'm unsure about.

What I have done:
![componentsstructure](https://user-images.githubusercontent.com/13721310/70866969-b7e50e80-1f78-11ea-8177-894f551380cd.PNG)

And I copied the contents of your library's files into those to files.

I then reference the Loading component like this on a page where I used it before (successfully):
![reference](https://user-images.githubusercontent.com/13721310/70866980-df3bdb80-1f78-11ea-97b6-115cbcc7d141.PNG)

I get an error, and I suppose its related to the way I reference the styles.css file:
![stylesreference](https://user-images.githubusercontent.com/13721310/70867000-01cdf480-1f79-11ea-9fe1-334e613ed00f.PNG)

The error reads:
Failed to compile.

./src/pages/Login.jsx
Module not found: You attempted to import ../../components/loader/Loading which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.

Again, I'm sorry, I'm a noob to web dev, but can code a little bit, your help is appreciated.

**Comment by willemevenwel** [comment]
Appologies, I got it working. That error was because referencing the component, from another directory, needed the path to be adjusted.

**Comment by willemevenwel** [comment]
![working](https://user-images.githubusercontent.com/13721310/70867188-5bcfb980-1f7b-11ea-9aff-167b88d6549b.PNG)

**Comment by shamin** [comment]
Great. Can I close this issue?

**Comment by willemevenwel** [comment]
Yes, definitely. Thanks again!!!
